import = [
"~/.config/alacritty/themes/themes/hyper.toml",
"~/.config/alacritty/keybindings.toml",
]

shell.program = "/usr/bin/zsh"
shell.args = ["-l"]

live_config_reload = true

[window]
# dimensions = { columns = 50, lines = 30}
padding = {x = 20, y = 20}
dynamic_padding = true
# decorations = "None"
opacity = 0.6
blur = true
startup_mode = "Maximized"
decorations_theme_variant = "Dark"

[font]
size=12

[terminal]
osc52 = "CopyPaste"
